CREATE TABLE WindowsEvents (
    ID_EVENT INT PRIMARY KEY,
    DATE DATETIME,
    HOST VARCHAR(255),
    SOURCE_ADDRESS VARCHAR(255),
    SOURCE_PORT INT,
    DEST_ADDRESS VARCHAR(255),
    DEST_PORT INT,
    PROTOCOL VARCHAR(50)
);

CREATE TABLE SwitchEvents (
    ID_EVENT INT PRIMARY KEY,
    DATE DATETIME,
    SOURCE VARCHAR(50),
    INFO TEXT
);
